### ISSUE TITLE
Crashing with dlss

### ISSUE THREAD

**Issue by Jadonik** [yobson1/REFramework#2]
With dlss and upscaler plugin will crash while loading.
Works fine otherwise.
[re2_framework_log.txt](https://github.com/yobson1/REFramework/files/11480199/re2_framework_log.txt)

**Comment by yobson1** [comment]
What graphics card are you using? The log suggests DLSS isn't supported on yours

**Comment by Jadonik** [comment]
Changing the location of the upscaler plugin from the plugins folder to the game root folder fixed it.
